---
- name: testing of the play 
  hosts: ec2-13-232-10-66.ap-south-1.compute.amazonaws.com
  tasks: 
  - name: Sync nrpe nagiosplug custom files
    synchronize:
     src: "/opt/test/abc.txt"
     dest: "/opt/test/xyz.txt"
     rsync_opts:
      - "--chown=ec2-user:root"
      - "--chmod=0775"
