- name: Start LogR system monitor service delayed
  hosts: all
  tasks:
   - win_service:
      name: AppReadiness
      start_mode: delayed
     register: delayed_task
   - name: workaround for delayed not appearing in the GUI
     win_command: sc.exe config MyService start= delayed-auto
     when: delayed_task is changed
