- name: Start LogR system monitor service delayed
  hosts: all
  tasks:
    - name: LogR System Monitor Service
      win_service:
        name: hkmsvc
        state: started
        start_mode: delayed
