- name: Adding the user to the Windows system
  hosts: all
  tasks: 
   - name: Adding the user to the system
     win_user:
      name: redhat
      password: Google@123
      state: present
      groups:
       - Users
       - Developers
      groups_action: replace
