- name: testing the copy of the files
  hosts: all 
  tasks: 
   - name: Copy a single file
     win_copy:
      src: C:\Users\Administrator\Desktop\testing.txt
      dest: C:\Users\Administrator\Desktop\test.txt

