
- name: Install packages on systems
  hosts: all
  vars:
   packages:
    - git
    - Notepad++
  
  tasks:
   - name: Installing Chocolatey 
     win_chocolatey:
      name: chocolatey
      state: present
    
   - name: Installing Packages
     win_chocolatey:
      name: "{{ packages }}"
      state: present
      pinned: true
