
- name: testing the copy/searching/modify of the files
  hosts: all 
  tasks: 
  
   - name: Copy a single file
     win_copy:
      src: C:\Users\Administrator\Desktop\testing.txt.txt
      dest: C:\Users\Administrator\Desktop\test.txt
      remote_src: yes
      
   - name: testing the seraching with win_find
     win_find:
      paths: C:\Users\Administrator\Desktop
      hidden: yes
      patterns: '*.txt'
   
   - name: Modifying a line in the service file
     win_lineinfile:
      path: C:\Users\Administrator\Desktop\test.txt
      regexp: '^testing'
      line: '# line modified by ansible'
